language: "node_js"
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - "node_modules"
script:
  - npm run validate
  - npm run build
after_success:
  - "./node_modules/.bin/codecov"
deploy:
  provider: npm
  email: "$NPM_LOGIN"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
